// <auto-generated />
using Conductor.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Conductor.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20171229065141_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Conductor.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComputerName");

                    b.Property<int?>("EnsembleId");

                    b.Property<string>("Key");

                    b.Property<string>("MacAddress");

                    b.HasKey("Id");

                    b.HasIndex("EnsembleId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Conductor.Entities.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArtistId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Key");

                    b.Property<string>("Output");

                    b.Property<DateTime?>("ProcessedAt");

                    b.Property<string>("Script");

                    b.Property<bool>("Success");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Compositions");
                });

            modelBuilder.Entity("Conductor.Entities.Ensemble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Name");

                    b.Property<string>("RegistrationKey");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Ensembles");
                });

            modelBuilder.Entity("Conductor.Entities.Artist", b =>
                {
                    b.HasOne("Conductor.Entities.Ensemble", "Ensemble")
                        .WithMany("Artists")
                        .HasForeignKey("EnsembleId");
                });

            modelBuilder.Entity("Conductor.Entities.Composition", b =>
                {
                    b.HasOne("Conductor.Entities.Artist", "Artist")
                        .WithMany("Compositions")
                        .HasForeignKey("ArtistId");
                });
#pragma warning restore 612, 618
        }
    }
}
